# Generated by Django 3.2.9 on 2021-12-16 22:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Producto')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad del producto:')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('t_lista', models.CharField(default='', max_length=50, verbose_name='Topping')),
                ('estado', models.BooleanField(default=False, verbose_name='Confirmacion de compra')),
                ('Envio', models.BooleanField(default=False, verbose_name='Confirmacion de Envio')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Extra', models.CharField(max_length=30)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPizza', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('P_Small', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('P_Large', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('img_producto', models.ImageField(blank=True, null=True, upload_to=orders.models.filepath)),
                ('Topping_Estado', models.BooleanField(default=False)),
                ('Extra_Estado', models.BooleanField(default=False)),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categoria')),
                ('Extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.extra')),
                ('TipoPizza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.tipopizza')),
                ('Topping', models.ManyToManyField(blank=True, null=True, to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(default=datetime.datetime(2021, 12, 16, 16, 55, 58, 203226))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
