# Generated by Django 3.2.9 on 2021-12-17 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211216_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Topping',
        ),
        migrations.AlterField(
            model_name='cart',
            name='creado',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 18, 47, 50, 342323)),
        ),
    ]
