# Generated by Django 3.2.9 on 2021-12-17 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211216_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_toppings',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='creado',
            field=models.DateField(default=datetime.datetime(2021, 12, 16, 22, 33, 24, 680580)),
        ),
    ]
