# Generated by Django 3.2.9 on 2021-12-17 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='creado',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 0, 26, 31, 981972)),
        ),
    ]
