# Generated by Django 3.2.9 on 2021-12-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cart_creado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
