# Generated by Django 3.2.9 on 2021-12-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='username',
            field=models.CharField(default=1, max_length=50, verbose_name='Cliente'),
            preserve_default=False,
        ),
    ]
