# Generated by Django 3.2.9 on 2021-12-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cartitems_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='t_lista',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='t_lista',
            field=models.CharField(default=1, max_length=100, verbose_name='Toppings'),
            preserve_default=False,
        ),
    ]
