# Generated by Django 3.2.9 on 2021-12-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20211217_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='l_extra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra'),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='t_lista',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Toppings'),
        ),
    ]
